package slashee.main;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Slashee {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	System.out.println("Hello world");
    }
}
