package slashee.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import slashee.main.*;

import static org.junit.Assert.*;

public class ConfigHandlerTest {
    @Test public void testConfigHandler() {
        assertNotNull(ConfigHandler.getSlackToken());
        assertNotNull(ConfigHandler.getSlackUrl());
        assertNotNull(ConfigHandler.getEmailKey());
        assertNotNull(ConfigHandler.getAlternateEmailKey());
        assertNotNull(ConfigHandler.getIncludeDeletedUsers());
        assertNotNull(ConfigHandler.getIncludeHiddenFields());
    }
}
