package slashee.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import slashee.main.*;

import static org.junit.Assert.*;

public class SlasheeTest {
    @Test public void testSlashee() {
    	
        assertNotNull(ConfigHandler.getSlackToken());
        assertNotNull(ConfigHandler.getSlackUrl());
        assertNotNull(ConfigHandler.getEmailKey());
        assertNotNull(ConfigHandler.getAlternateEmailKey());
        assertNotNull(ConfigHandler.getIncludeDeletedUsers());
        assertNotNull(ConfigHandler.getIncludeHiddenFields());
        
        assertNotNull(SlackHandler.getUserIds());
        assertFalse(SlackHandler.getUserIds().isEmpty());
        assertNotNull(SlackHandler.getIdToLabelMap());
        assertFalse(SlackHandler.getIdToLabelMap().isEmpty());
        assertNotNull(SlackHandler.getProfilePerUser());
        assertFalse(SlackHandler.getProfilePerUser().isEmpty());
    }
}
