package slashee.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import slashee.main.Slashee;

import static org.junit.Assert.*;

public class SlasheeTest {
    @Test public void testSlashee() {
        assertNotNull(Slashee.getSlackToken());
    }
}
